config/routes.rb
Tretauto::Application.routes.draw do
  root :to => 'autos#index'
  resources :autos

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :auto
  has_attached_file :asset, :styles => { :large => "640x480", :medium => "300.300>", :small => "150x150>" ,:thumb => "60x45>" }
end

app/models/auto.rb
class Auto < ActiveRecord::Base
  attr_accessible :hersteller, :modell, :land, :baujahr, :typ, :datenbanknr, :datenbanknralt, :status, :farbe, :antrieb, :konstruktion, :raeder, :ausstattung, :abmessungl, :abmessungb, :abmessungh, :gewichtinkg, :relevanz, :geschaetztermarktwert, :sonstiges, :anmerkungen, :kaufdatum, :ebaybenutzername, :verkaeufer, :ebayartikelnummer, :modellbeschreibung, :farbekauf, :anmerkungnachkauf, :zahlungsart, :zahlungsdatum, :waehrung, :kaufpreis, :transport, :summe, :ersatzteile, :restaurier, :gesamt, :assets_attributes, :fw, :fwkaufpreis, :fwtransport, :fwsumme, :fwersatzteile, :fwrestaurier, :fwgesamt
  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true
  
  def next
       self.class.find :first,
            :conditions => ["id > ?",self.id],
            :order => "id ASC"
    end

    def previous
       self.class.find :first,
            :conditions => ["id < ?",self.id],
            :order => "id DESC"
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_filter :authenticate
  
  def index
    @autos = Auto.all
  end

  def show
    @auto = Auto.find(params[:id])
  end

  def new
    @auto = Auto.new
    2.times {@auto.assets.build}
  end

  def create
    @auto = Auto.new(params[:auto])
    if @auto.save
      redirect_to @auto, :notice => "Successfully created auto."
    else
      render :action => 'new'
    end
  end

  def edit
    @auto = Auto.find(params[:id])
    2.times {@auto.assets.build}
  end

  def update
    @auto = Auto.find(params[:id])
    if @auto.update_attributes(params[:auto])
      redirect_to @auto, :notice  => "Successfully updated auto."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @auto = Auto.find(params[:id])
    @auto.destroy
    redirect_to autos_url, :notice => "Successfully destroyed auto."
  end
  
  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "anemon" && password == "lotus"
    end
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/autos/edit.html.erb
<img src="/images/tretauto-logo.jpg" alt="Tretauto Logo">

<%= render 'form' %>

<p class="left">
	Blättern: 
	<%= link_to("voriger", @auto.previous ) if @auto.previous %>
	<%=	"voriger" if !@auto.previous %> | 
	<%= link_to("nächster", @auto.next) if @auto.next %>
	<%=	"nächster" if !@auto.next %>
	Datensatz
</p>


<div class="button">
  <%= link_to "Auto anzeigen", @auto %>
  <%= link_to "Alle Autos anzeigen", autos_path %>
</div>

app/views/autos/index.html.erb
<img src="/images/tretauto-logo.jpg" style="float:left; margin-right: 100px;" alt="Tretauto Logo">
<table id="example">
	<thead>
  		<tr>
			<th width=120 >&nbsp;</th>
			<th width=40 >ID</th>
			<th width=40>Alt</th>
		    <th width=120>Hersteller</th>
		    <th width=220>Modell</th>
		    <!--<th>Land</th>
		    <th>Baujahr</th>
		    <th>Typ</th>
		    <th>Datenbanknr</th>
		    <th>Datenbanknralt</th>
		    -->
		    <th width=120>Farbe</th>
			<th>Status</th>
		    <!-- <th>Antrieb</th>
		    <th>Konstruktion</th>
		    <th>Raeder</th>
		    <th>Ausstattung</th>
		    <th>Abmessungl</th>
		    <th>Abmessungb</th>
		    <th>Abmessungh</th>
		    <th>Gewichtinkg</th>
		    <th>Relevanz</th>
		    <th>Geschaetztermarktwert</th>
		    <th>Sonstiges</th>
		    <th>Anmerkungen</th>
		    <th>Kaufdatum</th>
		    <th>Ebaybenutzername</th>
		    <th>Verkaeufer</th>
		    <th>Ebayartikelnummer</th>
		    <th>Modellbeschreibung</th>
		    <th>Farbekauf</th>
		    <th>Anmerkungnachkauf</th>
		    <th>Zahlungsart</th>
		    <th>Zahlungsdatum</th>
		    <th>Waehrung</th>
		    <th>Kaufpreis</th>
		    <th>Transport</th>
		    <th>Summe</th>
		    <th>Ersatzteile</th> 
		    <th>Restaurier</th>
		    <th>Gesamt</th> -->
			<th></th>
			<th></th>
			<th></th>
		  </tr>
		</thead>
	<tbody>
  <% for auto in @autos %>
    <tr onclick="">
		<td><span style="margin-left: 10px">
		<% auto.assets.each_with_index  do |asset, i|
			
			 %>
		
				
			<!-- <%= asset.thumbnail %> -->
			<% if asset.thumbnail == true %>
			<%= image_tag(asset.asset.url(:thumb)) %>          
			<% end %>
			
			
		<% end %>
		</span>
	</td>
	  <td><%= auto.id %></td>
	  <td><%= auto.datenbanknralt %></td>
      <td><%= auto.hersteller %></td>
      <td><%= auto.modell %></td>
      <!-- <td><%= auto.land %></td>
      		<td><%= auto.baujahr %></td>
            <td><%= auto.typ %></td>
            <td><%= auto.datenbanknr %></td>
            <td><%= auto.datenbanknralt %></td>
            -->
            <td><%= auto.farbe %></td>
			<td><%= auto.status %></td>
            <!-- <td><%= auto.antrieb %></td>
            <td><%= auto.konstruktion %></td>
            <td><%= auto.raeder %></td>
            <td><%= auto.ausstattung %></td>
            <td><%= auto.abmessungl %></td>
            <td><%= auto.abmessungb %></td>
            <td><%= auto.abmessungh %></td>
            <td><%= auto.gewichtinkg %></td>
            <td><%= auto.relevanz %></td>
            <td><%= auto.geschaetztermarktwert %></td>
            <td><%= auto.sonstiges %></td>
            <td><%= auto.anmerkungen %></td>
            <td><%= auto.kaufdatum %></td>
            <td><%= auto.ebaybenutzername %></td>
            <td><%= auto.verkaeufer %></td>
            <td><%= auto.ebayartikelnummer %></td>
            <td><%= auto.modellbeschreibung %></td>
            <td><%= auto.farbekauf %></td>
            <td><%= auto.anmerkungnachkauf %></td>
            <td><%= auto.zahlungsart %></td>
            <td><%= auto.zahlungsdatum %></td>
            <td><%= auto.waehrung %></td>
            <td><%= auto.kaufpreis %></td>
            <td><%= auto.transport %></td>
            <td><%= auto.summe %></td>
            <td><%= auto.ersatzteile %></td>
            <td><%= auto.restaurier %></td>
            <td><%= auto.gesamt %></td> -->
      <td width= 45><%= link_to image_tag("/images/view.png", :border=>0), auto %></td>
      <td width= 45><%= link_to image_tag("/images/edit.png", :border=>0), edit_auto_path(auto) %></td>
	  <td width= 45><%= link_to image_tag("/images/delete.png", :border=>0), auto, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>

  <% end %>
</tbody>
</table>

<p class="button"><%= link_to "Neues Auto anlegen", new_auto_path %></p>

app/views/autos/new.html.erb
<img src="/images/tretauto-logo.jpg" alt="Tretauto Logo">
<% title "New Auto" %>

<%= render 'form' %>

<p><%= link_to "Zurück zur Liste", autos_path %></p>

app/views/autos/show.html.erb
<div><img src="/images/tretauto-logo.jpg" alt="Tretauto Logo"></div>
<div class="narrow" style="width: 335px; float: left; margin-left: -9px;">
<p class="left" style="width: 50px">
	<label>id</label><br />
	<span class="textfieldid"><%= @auto.id %></span>
</p>
<p class="left hersteller">
  <label>Hersteller</label><br />
  <span class="textfieldherst"><%= @auto.hersteller %>&nbsp;</span>
</p>
<p class="modell_">
  <label>Modell</label><br />
  <span class="textfieldherst"><%= @auto.modell %>&nbsp;</span>
</p>
<p class="firstc left">
  <label>Land</label><br />
  <span class="textfield"><%= @auto.land %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Baujahr</label><br />
  <span class="textfield"><%= @auto.baujahr %>&nbsp;</span>
</p>
<br style="clear: both;">
<p class="typ">
  <label>Typ</label><br />
  <span class="textfieldbig"><%= @auto.typ %>&nbsp;</span>
</p>
<p class="firstc left">
  <label>Status</label><br />
  <span class="textfield"><%= @auto.status %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Farbe</label><br />
  <span class="textfield"><%= @auto.farbe %>&nbsp;</span>
</p>
<p class="firstc left">
  <label>Konstruktion</label><br />
  <span class="textarea"><%= @auto.konstruktion %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Antrieb</label><br />
  <span class="textarea"><%= @auto.antrieb %>&nbsp;</span>
</p>
<p class="firstc left">
  <label>Raeder</label><br />
  <span class="textarea"><%= @auto.raeder %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Ausstattung</label><br />
  <span class="textarea"><%= @auto.ausstattung %>&nbsp;</span>
</p>
<p class="firstc left">
	  <label>Abmessungen LxBxH</label><br />
	  <span class="textfieldsmal left"><%= number_with_precision(@auto.abmessungl, :precision => 1) %>&nbsp;</span>
	  <span class="textfieldsmal left"><%= number_with_precision(@auto.abmessungb, :precision => 1) %>&nbsp;</span>
	  <span class="textfieldsmal left"><%= number_with_precision(@auto.abmessungh, :precision => 1) %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Gewicht in kg</label><br />
  <span class="textfield"><%= number_with_precision(@auto.gewichtinkg, :precision => 2) %>&nbsp;</span>
</p>
<br style="clear:both">
<p class="firstc left">
  <label>Relevanz</label><br />
  <span class="textfield"><%= @auto.relevanz %>&nbsp;</span>
</p>
<p class="secondc left">
  <label>Marktwert geschätzt</label><br />
  <span class="textfield"><%= number_with_precision(@auto.geschaetztermarktwert , :precision => 2) %>&nbsp;</span>
</p>
<br style="clear:both">
<p>
  <label>Sonstiges</label><br />
  <span class="textfieldsonstiges"><%= @auto.sonstiges %>&nbsp;</span>
</p>

</div>
<div style="width: 230px; float: left; padding:25px 10px;">
<p>
	<% @auto.assets.each_with_index do |asset| %>

		<p><%= link_to image_tag(asset.asset.url(:small)), asset.asset.url(:original) %></p>
	
	<% end %>
</p>
</div>

<div class="narrow" style="width: 335px; float: left; background: #ccc;">

<p class="left" style="width: 51px">
  <label>DB. alt</label><br />
  <span class="textfieldid dark"><%= @auto.datenbanknralt %>&nbsp;</span>
</p>
<p class="left margin">
  <label>Kaufdatum</label><br />
  <span class="textfieldundef_ dark"><%= @auto.kaufdatum %>&nbsp;</span>
</p>
<p class="left" style="margin-left: -2px">
  <label>Verkaeufer</label><br />
  <span class="textfield_ dark"><%= @auto.verkaeufer %>&nbsp;</span>
</p>
<p class="left firstc">
  <label>Ebay benutzername</label><br />
  <span class="textfield_ dark"><%= @auto.ebaybenutzername %>&nbsp;</span>
</p>
<p class="left secondc">
  <label>Ebay artikelnummer</label><br />
  <span class="textfield_ dark"><%= @auto.ebayartikelnummer %>&nbsp;</span>
</p>
<br style="clear:both;">
<p>
  <label>Modellbeschreibung</label><br />
  <span class="textfieldbig_ dark"><%= @auto.modellbeschreibung %>&nbsp;</span>
</p>
<p class="left firstc">
  <label>Farbe kauf</label><br />
  <span class="textfield_ dark"><%= @auto.farbekauf %>&nbsp;</span>
</p>
<p class="left secondc">
  <label>Anmerkung nach kauf</label><br />
  <span class="textfield_ dark"><%= @auto.anmerkungnachkauf %></span>
</p>
<br style="clear:both;">
<p class="left firstc">
  <label>Zahlungsart</label><br />
  <span class="textfield_ dark"><%= @auto.zahlungsart %></span>
</p>
<p class="left secondc">
  <label>Zahlungsdatum</label><br />
  <span class="textfield_ dark"><%= @auto.zahlungsdatum %></span>
</p>
<br style="clear:both;">
<p class="left" style="width:25%;">
  <label>Waehrung</label><br />
  <span class="textfieldmid dark"><%= @auto.waehrung %></span>
</p>
<p class="left" style="width:25%;">
  <label>Kaufpreis</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.kaufpreis, :precision => 2) %></span>
</p>
<p class="left" style="width:25%;">
  <label>Transport</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.transport, :precision => 2) %></span>
</p>
<p class="left" style="width:25%;">
  <label>Summe</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.summe, :precision => 2) %></span>
</p>

<p class="left" style="width:25%;">
	&nbsp;
</p>

<p class="left" style="width:25%;">
  <label>Ersatzteile</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.ersatzteile, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Restaurier</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.restaurier, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Gesamt</label><br />
  <span class="textfieldmid dark "><%= number_with_precision(@auto.gesamt, :precision => 2) %>&nbsp;</span>
</p>
<br style="clear:both;">

<p class="left" style="width:25%;">
  <label>Fremdw.</label><br />
  <span class="textfieldmid dark"><%= @auto.fw %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Kaufpreis</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.fwkaufpreis, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Transport:</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.fwtransport, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Summe:</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.fwsumme, :precision => 2) %>&nbsp;</span>
</p>

<p class="left" style="width:25%;">
	&nbsp;
</p>

<p class="left" style="width:25%;">
  <label>Ersatzteile:</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.fwersatzteile, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Restaurier:</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision(@auto.fwrestaurier, :precision => 2) %>&nbsp;</span>
</p>
<p class="left" style="width:25%;">
  <label>Gesamt:</label><br />
  <span class="textfieldmid dark alignright"><%= number_with_precision( @auto.fwgesamt, :precision => 2) %>&nbsp;</span>
</p>
</div>
<p style="clear: both; border-top: 1px solid #AE0D1B; margin-right: 10px;"></p>
<p class="left">
	Blättern: 
	<%= link_to("voriger", @auto.previous ) if @auto.previous %>
	<%=	"voriger" if !@auto.previous %> | 
	<%= link_to("nächster", @auto.next) if @auto.next %>
	<%=	"nächster" if !@auto.next %>
	Datensatz
</p>
<p class="button">
  <%= link_to "Editieren", edit_auto_path(@auto) %>
  <%= link_to "Löschen", @auto, :confirm => 'Are you sure?', :method => :delete %>
  <%= link_to "Alle Autos anzeigen", autos_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Tretauto Datenbank" %></title>
    <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.dataTables' %> 
	<%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag 'demo_page' %>
	<%= stylesheet_link_tag 'print' , :media => :print %>

    <%= csrf_meta_tag %>
    <%= yield(:head) %>
	<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		$('#example').dataTable( {
				"sPaginationType": "full_numbers",
				"aaSorting": [[ 1, "asc" ]]
		} );
		
		
		
		$('.file-field').attr('size', 12);
			
	} );
	</script>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>